### ISSUE TITLE
Making server layer dependent on configuration layer

### ISSUE THREAD

**Issue by markosski** [scalapb/zio-grpc#109]
In provided examples port is provided explicitly, e.g.
```
val serverLayer =
    ServerLayer.fromServiceLayer(
        io.grpc.ServerBuilder.forPort(9000)
    )(myServiceLive)
```
I have a configuration layer and would like to pass port number from it into serverLayer, what's the best way to accomplish this?

**Comment by thesamet** [comment]
Hi @markosski ,
The following code would work in the context of the HelloWorldServer example https://github.com/scalapb/zio-grpc/blob/master/examples/src/main/scala/zio_grpc/examples/helloworld/HelloWorldServer.scala:

```
case class Config(port: Int)

object HelloWorldServer extends zio.App {
  val serviceLive = GreeterImpl.toLayer
  val configLayer = ZLayer.succeed(Config(9000))
  val serverLayer =
    ZLayer.fromServicesManaged((service: ZGreeter[Any, Any], config: Config) =>
      ManagedServer.fromService(ServerBuilder.forPort(config.port), service)
    )
  val ourApp = (serviceLive ++ configLayer) >>> serverLayer

  def run(args: List[String]) = ourApp.build.useForever.exitCode
}
```

**Comment by markosski** [comment]
Hi @thesamet this solved my problem, thank you!
