### ISSUE TITLE
io.grpc.ManagedChannelProvider$ProviderNotFoundException

### ISSUE THREAD

**Issue by markosski** [scalapb/zio-grpc#110]
I'm getting following error with assembled (fat jar) GRPC client application. Everything works fine when running directly in sbt which makes me think assembly is excluding something.

```
io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
║  ║    at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:65)
║  ║    at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
```

Using following deps:
```
"com.thesamet.scalapb" %% "scalapb-runtime-grpc" % scalapb.compiler.Version.scalapbVersion
"io.grpc" % "grpc-netty" % "1.31.1"
"dev.zio" %% "zio" % "1.0.1"
```

SBT Assembly configuration:
```
assemblyMergeStrategy in assembly := {
    case PathList("META-INF", xs @ _*) => MergeStrategy.discard
    case PathList("reference.conf") => MergeStrategy.concat // configs
    case x =>
        val oldStrategy = (assemblyMergeStrategy in assembly).value
        oldStrategy(x)
   }
```

Example Client Layer:
```
val clientLayer: Layer[Throwable, AccountServiceClient] =
                        AccountServiceClient.live(
                            ZManagedChannel(
                                ManagedChannelBuilder
                                    .forAddress(
                                        config.grpcServices.scheduler.host, 
                                        config.grpcServices.scheduler.port)
                                    .usePlaintext
                            )
                        )
```

**Comment by thesamet** [comment]
Here it's been suggested to move to grpc-netty-shaded: https://github.com/googleapis/google-cloud-java/issues/2810

**Comment by thesamet** [comment]
Looks like I once added a note on it on ScalaPB's docs: https://scalapb.github.io/docs/grpc/#grpc-netty-issues

**Comment by markosski** [comment]
Thanks @thesamet 
I had similar error with server app and used `NettyServerBuilder` directly which solved it. 
On the client side I tried `grpc-netty-shaded` but doesn't seem to be solving the issue.

**Comment by markosski** [comment]
@thesamet actually found some older gitter discussion where you suggested to use following merge rule which seemed to fix it :)

```
assemblyMergeStrategy in assembly := {
    case x if x.contains("io.netty.versions.properties") => MergeStrategy.discard
    case x =>
        val oldStrategy = (assemblyMergeStrategy in assembly).value
        oldStrategy(x)
}
```

**Comment by thesamet** [comment]
Interesting! Can you submit an edit to this docs summarizing the solutions we have: https://github.com/scalapb/ScalaPB/edit/master/docs/src/main/markdown/grpc.md

**Comment by markosski** [comment]
Submitted PR https://github.com/scalapb/ScalaPB/pull/909, closing this issue.
