### ISSUE TITLE
Update callOptions with ZClientInterceptor

### ISSUE THREAD

**Issue by tuleism** [scalapb/zio-grpc#123]
Is it possible to change `callOptions` within `ZClientInterceptor.interceptCall`? My use case is to use an interceptor to set deadline for every request.

**Comment by thesamet** [comment]
I think this should be possible by intercepting the call and passing an updated `callOptions`, see similar code here that modifies the metadata: https://github.com/scalapb/zio-grpc/blob/master/core/shared/src/main/scala/scalapb/zio_grpc/ZClientInterceptor.scala

I haven't tried this, but I expect this to be fairly simply. It would be great if you can report here what you find.

**Comment by tuleism** [comment]
@thesamet 

It seems not possible now. On a `ClientCall` or `ZClientCall`, we cannot update the `callOptions`. The only way to do it is to pass the updated `callOptions` to a `channel.newCall`. However, `ZClientInterceptor.interceptCall` doesn't provide a reference to `channel`.

zio-grpc:

```scala
  def interceptCall[Req, Res](
      methodDescriptor: MethodDescriptor[Req, Res],
      call: CallOptions,
      clientCall: ZClientCall[R, Req, Res]
  ): ZClientCall[R, Req, Res]
```

java-grpc:

```java
  <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(
      MethodDescriptor<ReqT, RespT> method, CallOptions callOptions, Channel next);
```

Another scenario is that I want to set custom deadline per call - e.g with ScalaPB: `stub.withDeadlineAfter(2L, TimeUnit.SECONDS).call()`. The special thing about `withDeadlineAfter` is that it is an effect - the deadline is set to be current time + 2 seconds. Right now, the generated code only allows setting `callOptions` at creation time:

```scala
def live[R](managedChannel: scalapb.zio_grpc.ZManagedChannel[R], options: io.grpc.CallOptions = io.grpc.CallOptions.DEFAULT, headers: zio.UIO[scalapb.zio_grpc.SafeMetadata] = scalapb.zio_grpc.SafeMetadata.make)
```

**Comment by thesamet** [comment]
I added support for setting deadlines per request, documented here and available in the latest snapshot: https://scalapb.github.io/zio-grpc/docs/deadlines
