### ISSUE TITLE
Handle ZIO failures/causes?

### ISSUE THREAD

**Issue by RicoGit** [scalapb/zio-grpc#125]
I'd like to handle all  ZIO `Cause`, like this `call.catchAllCause` in one place with some custom logic. Is it possible to add somehow `ServerInterceptor` or stuff like that and recover from Zio causes and return `Status.Internal` for clients?

**Comment by thesamet** [comment]
Yes. We have an abstraction called [ZTransform](https://github.com/scalapb/zio-grpc/blob/f005ac792d492ddc97771a7b14e008d47bdb6dc4/core/shared/src/main/scala/scalapb/zio_grpc/ZTransform.scala#L8-L17) that lets you transform all effects/streams that are returned by a service in the same way. In your case, you want to apply `catchAllCause` to all of them.

The steps are:
1. Create a ZTransform object that represents the effect you want to apply by extending the ZTransform trait.
2. Use ServiceTrait.transformableService.transform(serviceInstance, yourZtransform) to return a new instance of the service with the ZTransform applied to it.

It looks like `TransformableOps` doesn't have `transform` yet (which could result in a simpler syntax for the second step...)

**Comment by RicoGit** [comment]
Cool, thanks.
