### ISSUE TITLE
Backpressure support

### ISSUE THREAD

**Issue by fillson-shady** [scalapb/zio-grpc#14]
Hello!
First of all thank you for the great library! That is what I was looking for.  

I have question about backpressure support in streaming scenarios.
I have created simple test with client streaming to server with a large chunks of bytes. It works great with a performance near native java-gRPC libraries shows. However, when I have added `ZIO.sleep` to a service logic, test became crushing with an `OutOfMemory` error (on both client and server side).

There is a great library [salesforce/reactive-grpc](https://github.com/salesforce/reactive-grpc) which provides backpressure support for java world. Is there any plans to implement such functionality in zio-grpc?

Btw, there is a simple workaround can be used for now:
```scala
def clientLogic = for {
  data      <-  //some big, maybe unbounded data stream
  queue     <- Queue.bounded[Request](10)     //10 is buffer size
  _         <- queue.offerAll(data.take(10))  //initial request for a data
  _         <- GeneratedService
    .send(Stream.fromQueue(queue))
    .tap(demand => queue.offerAll(data.take(demand.count)))
    .runDrain
} yield ()
```
Here client sends some amount of data to the server and after some processing server responses to client with a `Demand(count: Int)` message, which signalises that server is ready accept more data.

**Comment by thesamet** [comment]
Hey @fillson-shady . I haven't been thinking about backpressure yet, but happy to get the discussion started and having this implemented soon. Will you be able to contribute a PR? If so, can you briefly describe the design/implementation?

**Comment by fillson-shady** [comment]
Hi @thesamet , thank you for quick reply!
Unfortunately my workaround can't be used in a general way - it forces you to use special messages for server responses. So I have to investigate the salesforce/reactive-grpc implementation and than adopt it to ZIO ecosystem. It may take a lot of time, but anyway I will write here as soon as I get any results.

**Comment by fillson-shady** [comment]
@thesamet hello again!
Finally I have an opportunity to look on this.
Let's consider one-way streaming case with a slow consumer. With the current approach we have 2 problem places:  
- out of memory on consumer, because it consumes all incoming messages in the unbounded queue
- out of memory on producer - if consumer doesn't accept more messages, producer will overflow it's internal gRPC send buffer, because producer doesn't aware of consumer 'ready to accept' status  

First one is easy to solve - we should request new message only after processing already received one. We can reach it by moving call of `call.request(1)` from:
```scala
override def onMessage(message: Res): Unit =
    runtime.unsafeRun(queue.offer(Right(message)) *> call.request(1))
```
to the data stream processing stage:
```scala
def stream: ZStream[R, Status, Res] =
  ZStream.fromQueue(queue) /*some other code*/ .tap(_ => call.request(1))
```
If buffering is needed, a library user can always add the `stream.buffer(x)` stage.

Second one is more tricky - we need to know, when a consumer is ready to accept more data. The only way to do this is by using `StreamObserver` classes (in a client for a client streaming case and in a server for a server streaming).  
There is corresponding utility methods if gRPC: `ClientCalls.asyncClientStreamingCall` and `ServerCalls.asyncServerStreamingCall`.  
With this approach we must convert outgoing data stream into a queue, so we can take a data from the queue when consumer is ready:  
```scala
streamObserver.setOnReadyHandler { () =>
  runtime.unsafeRunSync {
    recursivelyTake(check = Task(streamObserver.isReady), action = requestQueue.take)
  }
}
```  

Unfortunately where is no direct mapping between gRPC's Call api and StreamObserver api, so we also should refactor some cases like handling of metadata, errors, events and so on.

I'll be glad to get a feedback about my thoughts, and then start to work on this task.

**Comment by thesamet** [comment]
For the second problem, I see that `ServerCall` has an `isReady` method: https://grpc.github.io/grpc-java/javadoc/io/grpc/ServerCall.html#isReady--  . Can we use that to simplify the solution?

**Comment by ahjohannessen** [comment]
@thesamet see https://github.com/fiadliel/fs2-grpc/pull/39 for inspiration. I guess that PR needs to be worked through and merged as well.

**Comment by thesamet** [comment]
Yes, I was thinking of a solution that worked like this (sleep while not ready, otherwise send)

**Comment by ahjohannessen** [comment]
Java example from grpc:

```java
public void onReady() {
       while (call.isReady()) {
         FooRequest nextRequest = makeNextRequest();
         if (nextRequest == null) {  // No more requests to send
           call.halfClose();
           return;
         }
         call.sendMessage(nextRequest);
       }
     }
   }
```
However, it is noted in grpc-java api docs that methods that only send one message, i.e unary and server streaming should not use `isReady`

**Comment by fillson-shady** [comment]
> For the second problem, I see that `ServerCall` has an `isReady` method: https://grpc.github.io/grpc-java/javadoc/io/grpc/ServerCall.html#isReady-- . Can we use that to simplify the solution?

Oh, I've just missed this APIs. Sure, we can use `isReady` and `onReady` in both client and server calls.  

@ahjohannessen thanks for example!

**Comment by fillson-shady** [comment]
Hi @thesamet! I made a PR: #152
I also want to add some tests, but it's not so obvious:

- we can't count outgoing messages in sender because of internal gPRC/TCP buffers
- we can't count incoming messages in slow consumer because they can be placed in internal `Queue`
- we can't just send an infinite stream to a slow consumer, because in case of failure we can get OOM and non terminating jvm

So, I think of two possible ways:

- test bidi streaming scenario - producer tries to send many messages, consumer slowly consumes some of them (in a fork) and sends ack back to producer. Then producer checks how many messages does consumer actually get
- introduce some testable replacements for `ZChannel ` and `ZCall`, however it can complicate codebase

What do you think?

**Comment by phderome** [comment]
> Yes, I was thinking of a solution that worked like this (sleep while not ready, otherwise send)

How about using `ZStream.effectAsyncMaybe` and not sleep? 
```
       testM("effectAsyncMaybe back pressure") {
          for {
            refCnt  <- Ref.make(0)
            refDone <- Ref.make[Boolean](false)
            stream = ZStream.effectAsyncMaybe[zio.console.Console, Throwable, Int](
                       cb => {
                         global.execute { () =>
                           // 1st consumed by sink, 2-6 – in queue, 7th – back pressured, refCnt.set is a simulation of
                           // this stream would be created from a queue published by producing stream.
                           (1 to 7).foreach(i => cb(refCnt.set(i) *> zio.console.putStrLn(s"HELLO $i") *> ZIO.succeedNow(Chunk(i))))
                           cb(zio.console.putStrLn("SETTING TRUE")  *> refDone.set(true) *> ZIO.fail(None)) // simulates
                           // ending the stream delivery.
                         }
                         None
                       },
              5  // outputbuffer of values outside of 5,6 fail test (6 presumably because of 1 entering queue?)
                     )
            run    <- stream.run(ZSink.fromEffect[Any, Nothing, Int, Nothing](ZIO.never)).fork // processes the stream
            failed7      <- refCnt.get.repeatWhile(_ != 7)  // "consumes" all, really a "proof" that we published all.
            _ <- zio.console.putStrLn(s"DEBUG 1 $failed7 $run")
            // simulates the slow consumer avoiding to take from 7.
            isDone <- refDone.get
            _ <- zio.console.putStrLn("DEBUG 2")
            _      <- run.interrupt
          } yield assert(isDone)(isFalse)
```

```
trait ZStreamPlatformSpecificConstructors {
  self: ZStream.type =>

  /**
   * Creates a stream from an asynchronous callback that can be called multiple times.
   * The optionality of the error type `E` can be used to signal the end of the stream,
   * by setting it to `None`.
   */
  def effectAsync[R, E, A](
    register: (ZIO[R, Option[E], Chunk[A]] => Unit) => Unit,
    outputBuffer: Int = 16
  ): ZStream[R, E, A] =
    effectAsyncMaybe(
      callback => {
        register(callback)
        None
      },
      outputBuffer
    )

```

See Itamar explain it in action at London 2019 (`registerTweetAlert` example): https://youtu.be/bbss7elSfxs?t=1501

**Comment by phderome** [comment]
I think the tests could use some enhancements as they pass on this incorrect "hot spinning solution". Possibly `InProcessServerBuilder` should be looked into.

```
trait ZCallBackpressure[-R, A] extends ZCall[R, A] {
  def sendMessageWhenReady(message: A): ZIO[R, Status, Unit] =
    ZIO.ifM(isReady)(
      sendMessage(message),
      sendMessageWhenReady(message)
    )

  def onReady(): ZIO[R, Status, Unit] = ZIO.unit
```

**Comment by regiskuckaertz** [comment]
We seem to be hit by the lack of backpressure in one of our services with Netty dying of an `java.lang.OutOfMemoryError: Direct buffer memory`. What can I do to help?

I looked at the akka-grpc implementation which can be summarised as:
- at start, pull an element from the source
- when receiving an element from the source, send it and, if client is ready, pull if not already pulled
- when client becomes ready, if not pulled already, try pulling an element from the source

It looks like we just need to create our own sink in here:
```
impl(req).provideEnvironment(ZEnvironment(requestContext)).foreach(call.sendMessage)
```
instead, roughly
```
val backpressure: ZSink[RequestContext, Status, Res, Nothing, Unit] = ???     
impl(req).run(backpressure).provideEnvironment(ZEnvironment(requestContext))
```
We can use the request context to store coordination structures if necessary, though perhaps there is a way to bypass the effect boundaries with the "unsafe" pattern in ZIO2.

**Comment by thesamet** [comment]
Hi @regiskuckaertz , thanks for bringing this up. I'll be open to a PR for rebasing the existing #152 PR or getting a new one if a simpler/better approach is available. The only reason that the original PR didn't make it in the first place was the extra complexity without real-world demand to warrant that.

**Comment by regiskuckaertz** [comment]
@thesamet could you cut a zio 1.x release please? or are snapshots available? eager to give https://github.com/scalapb/zio-grpc/pull/448 a run for its money on my app. btw if needed, where would you put configuration settings, like the size of the buffer?

**Comment by thesamet** [comment]
We have a snapshot for each commit at https://oss.sonatype.org/content/repositories/snapshots/com/thesamet/scalapb/zio-grpc/ . Can you try it out before we cut a release? For configuring, I suggest for now a JVM system property (`sys.Prop`) named `zio-grpc.backpressure-queue-size` that defaults to 16 if unset.

**Comment by regiskuckaertz** [comment]
@thesamet Yes, i will let you know asap.

**Comment by regiskuckaertz** [comment]
@thesamet actually sorry but I can't find the snapshot. Does it work for the 0.5 branch too? I tried https://oss.sonatype.org/content/repositories/snapshots/com/thesamet/scalapb/zio-grpc/zio-grpc-codegen_2.13/0.0.0+1-fcbebe07-SNAPSHOT/ but this is the zio 2 one from master.

**Comment by thesamet** [comment]
You're right! Snapshots were only being built from master. I've changed `release.yml` on 0.5.x so it gets snapshots too. The latest snapshot containing your change is `0.5.2+4-ef57448d-SNAPSHOT`.

**Comment by regiskuckaertz** [comment]
@thesamet all tests that were blowing up are passing now ,this is looking good!

**Comment by regiskuckaertz** [comment]
@thesamet do you want the config to be done immediately or are you ok with releasing now?

**Comment by thesamet** [comment]
Prefer with having the setting available on the release, so we have a way to have users reconfigure in case something comes up for them. Is behavior close to the original behavior achievable by setting the queue size to a very large number?

**Comment by regiskuckaertz** [comment]
Yes you are right, i will work on this asap b/c we need this fast for our project. 

> Is behavior close to the original behavior achievable by setting the queue size to a very large number?

Yes, then environmental context takes precedence above the overhead of the queue.

**Comment by thesamet** [comment]
Thanks for sending. I've released v0.5.3 with the PR merged. I've also published this page https://scalapb.github.io/zio-grpc/docs/backpressure - would appreciate if you can give it a quick read (it's super short) and let me know if anything need to be updated there.

**Comment by regiskuckaertz** [comment]
thank you 🙏 read it, it's great!

**Comment by thesamet** [comment]
Ported the server backpressure to ZIO2 in c42b410275c3455af121ff21d12787eb06c969c2
