### ISSUE TITLE
Kubernetes deployment - multiple replicas

### ISSUE THREAD

**Issue by tampler** [scalapb/zio-grpc#145]
Hello

I'm trying to deploy a demo service on a test cluster. It consists only a single Master node. 
If I increase replica set to > 1, Kubernetes fails to instantiate multiple pods due to the `port already in use` error (see the screenshot)

The service still works, but with a single replica per node.

How to scale this service, when each replica blocks the system port ? I can only think about setting replicas on multiple nodes, but wanna have few pods on a single node.

OS: Ubuntu 20.10 
Kuber: 1.19.3

```bash
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: <name>
  name: icare-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: <name>
  template:
    metadata:
      labels:
        app.kubernetes.io/name: <name>
    spec:
      containers:
      - image: <my-image>
        name: <myName>
        ports:
        - containerPort: 9090
          hostPort: 9090
```

![kuber](https://user-images.githubusercontent.com/2816743/97305941-ce354980-186e-11eb-8ecc-2b579027c898.png)

**Comment by thesamet** [comment]
From https://kubernetes.io/docs/concepts/configuration/overview/#services:

> Don't specify a hostPort for a Pod unless it is absolutely necessary. When you bind a Pod to a hostPort, it limits the number of places the Pod can be scheduled, because each <hostIP, hostPort, protocol> combination must be unique. If you don't specify the hostIP and protocol explicitly, Kubernetes will use 0.0.0.0 as the default hostIP and TCP as the default protocol.

**Comment by tampler** [comment]
Hi Nadav

Thanks for the info. Indeed, this solves my initial problem and I see 2 replicas of my `zio-grpc` service up and running. 

However, this gets me to another problem, possibly with `Kubernetes Ingress / Load Balancing` setup. Now I don't know how to get to my fixed port (9090), since it was not opened

I guess there should be another guide to setup `Kubernetes with Envoy proxy for gRPC`, something like [this](https://cloud.google.com/solutions/exposing-grpc-services-on-gke-using-envoy-proxy), but for a custom `k8s` deployment. Any thoughts about this?

**Comment by thesamet** [comment]
@tampler , envoy proxy would have to connect to the service exposed by Kubernetes, not a specific port on a host. See https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

**Comment by thesamet** [comment]
Re guide for custom k8s deployments - worth asking with the envoyproxy team.

**Comment by tampler** [comment]
Thank you ! Will take a look. Closing this since my initial problem was solved.
