### ISSUE TITLE
Do you have plans to derive REST services from GRPC specifications?

### ISSUE THREAD

**Issue by dpennell** [scalapb/zio-grpc#146]
Something like https://github.com/btlines/grpcgateway

**Comment by thesamet** [comment]
Hey @dpennell , there isn't such a plan. What use case do you have in mind? If the use case was to make it possible to connect from a browser through HTTP, I'd consider using grpc web (https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md) and use something like envoyproxy. This use case is supported for zio-grpc.

**Comment by dpennell** [comment]
I was just speculating about switching REST server frameworks to something with ZIO support and thought it would be nice to also get GRPC support.  I have no use-case for providing services by GRPC (yet...).

I'm happily using zio-grpc client for integrating with a third party GRPC service.

**Comment by thesamet** [comment]
There's https://github.com/grpc-ecosystem/grpc-gateway which can expose a restful interface to your grpc service. This way the service backend can be pure ZIO and zio-grpc, and work with ScalaPB case class, while all the json conversions and http are handled by the gateway.

**Comment by vyshane** [comment]
@dpennell Envoy can also provide HTTP/1 and JSON [transcoding](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter).

**Comment by thesamet** [comment]
Thanks for sharing @vyshane . Sounds like we have a pretty good answer for this issue.
