### ISSUE TITLE
flatPackage option

### ISSUE THREAD

**Issue by octavz** [scalapb/zio-grpc#162]
Hi,

When using `flatPackage` option I expected the ZIO code to be generated ignoring the file name. Is this by design or is a bug?

My use case is that the files are called with `xxx_yyy` and it appears `import com..xxx_yyy.ZioStuff._` and I would prefer not to have the `xxx_yyy` part in the `import`

Thank You.

**Comment by octavz** [comment]
even more if i use `flatPackage` it doesn't seem to work anymore since all the import are searching for `xxx_yyy`.

**Comment by thesamet** [comment]
ScalaPB and ZioCodeGenerator are two different code generators. If you pass `flatPackage` to ScalaPB, there's no way for ZioCodeGenerator to know that, so you'll end up with invalid references in the generated code. To make all generators see the same configuration, use package-scoped options: https://scalapb.github.io/docs/customizations/#package-scoped-options
