### ISSUE TITLE
Support for response Metadata (trailers)

### ISSUE THREAD

**Issue by ghostdogpr** [scalapb/zio-grpc#173]
Currently `unaryInputCallDriver` sends a hardcoded empty `Metadata` object when it calls `close`:
```scala
.onExit(ex => call.close(CallDriver.exitToStatus(ex), new Metadata).ignore)
```

It would be great to expose this so that the server can add metadata to the response.

**Comment by thesamet** [comment]
Sure - any thoughts for an API for that? What use case do you have in mind?

One way could be to enable this at bulk for an entire service (so individual method handlers don't have control, but there's a unified function that can take a generic response and add meta data). Alternatively, we change the effect type for each handler to allow for metadata.

**Comment by ghostdogpr** [comment]
In my case we need to send a custom error code to the client in case of error, so it would be per-call.

I initially used `put` on the existing `SafeMetadata` thinking that would be sent back to the client before realizing it didn't work (I guess it makes sense, you don't want to re-send all the received metadata). Since I need it both in case of error and success, maybe using the environment makes sense? Like a `responseMetadata` in `RequestContext`?

**Comment by thesamet** [comment]
Interesting idea for having the responseMetadata provided to the handler through `RequestContext` - that sounds like a way to achieve it with minimal breakage to the overall API.

**Comment by thesamet** [comment]
I checked in some initial implementation of the idea of using RequestContext. When trying to write some tests, I noticed that we also need to make the response headers available for the client. I think this can be done through the pre-existing client Context. Will follow through soon - would also appreciate if anyone can try to take it from here.

**Comment by penp3n** [comment]
For my use case, I am using a unified error type defined in my application domain for all APIs. I would like to transform that domain error type to a `Status` and response metadata containing containing a `com.google.rpc.ErrorInfo` object. Having a way to generically transform the error channel in this way would be ideal, but I understand that would introduce a breaking API change to the generated stubs (unless some new API was created, perhaps).

**Comment by penp3n** [comment]
> I checked in some initial implementation of the idea of using RequestContext. When trying to write some tests, I noticed that we also need to make the response headers available for the client. I think this can be done through the pre-existing client Context. Will follow through soon - would also appreciate if anyone can try to take it from here.

Hi @thesamet, I can try to get this over the finish line if you'd like. Are there any other pointers I should know about before jumping in?

**Comment by thesamet** [comment]
@penp3n thanks for the proposal to move forward with this. The furthest I got can be found in the `response_metadata` branch in this repo. It's been a while since I last looked into it, but I'll be happy to answer any specific questions you'll have as you go.

**Comment by notxcain** [comment]
@penp3n @thesamet hey what's the status of this?

**Comment by thesamet** [comment]
No updates on my end - this is still awaiting a PR.

**Comment by Gregory-Berkman-Imprivata** [comment]
@ghostdogpr any example of how trailers are populated from a request?

**Comment by frekw** [comment]
For anyone looking to use `com.google.rpc.Status` to provide more details (as I was), this seems to work (albeit a bit hacky):

```scala
  def toStatus = {
    val buildStatus = ZIO.attempt {
      val status = com.google.rpc.Status
        .newBuilder()
        .setCode(self.code.getCode().value())
        .setMessage(self.name)

      description match {
        case None        => ()
        case Some(value) =>
          status.addDetails(
            protobuf.Any.pack(
              ErrorInfo
                .newBuilder()
                .setReason(value)
                .build()
            )
          )
      }

      validationErrors match {
        case None        => ()
        case Some(value) =>
          status.addDetails(
            protobuf.Any.pack(
              com.google.rpc.BadRequest
                .newBuilder()
                .addAllFieldViolations(
                  value.map { e =>
                    com.google.rpc.BadRequest.FieldViolation
                      .newBuilder()
                      .setField(pathToString(e.path))
                      .setDescription(e.message)
                      .build()
                  }.toChunk.asJava
                )
                .build()
            )
          )
      }
      status.build()
    }

    (for {
      status <- buildStatus
      ctx    <- ZIO.service[RequestContext]
      _      <- ctx.responseMetadata.put(key, status)
    } yield self.code).orDie
```

**Comment by thesamet** [comment]
The code using `StatusException` is ready to be used in `rc5` of zio-grpc. I wasn't planning to backport this change to older versions of zio-grpc. Since it's a breaking change it would require a minor version bump for zio1 and I'm not sure if this is worthwhile to supoort two flavors (Status and StatusException) for zio1.

**Comment by thesamet** [comment]
This change is actually coming for https://github.com/scalapb/zio-grpc/issues/500, though still intended only for 0.6.0. Is there interest in seeing it for 0.5.x? Trying to understand if it's worthwhile and whether your project wouldn't be upgrading to zio2 in the near future anyway.

**Comment by Gregory-Berkman-Imprivata** [comment]
It would be nice to backport this change to 0.5.x and zio1. We will eventually look into upgrading our service to use zio2 but prioritizing work like this can be difficult. We have a more immediate need to support grpc error handling with metadata trailers.

**Comment by Gregory-Berkman-Imprivata** [comment]
> This change is actually coming for #500, though still intended only for zio-grpc 0.6.0. Is there interest in seeing it for 0.5.x? Trying to understand if it's worthwhile and whether your project wouldn't be upgrading to zio2 in the near future anyway.

I will try the upgrade to ZIO2
