### ISSUE TITLE
Bug - null value in proto class with no error

### ISSUE THREAD

**Issue by fokot** [scalapb/zio-grpc#179]
Hi @thesamet , I found my grpc server was not responding and it took me long time to find out what was wrong. I was interacting with java library and accidentally set `null` to `String` field in proto class. I didn't get any message from server and there was no error in logs. Even everything went ok in the gRPC method implementation. I didn't investigate it further but I will take a look on it how to fix it.

Example:
```
object GreeterImpl extends ZGreeter[ZEnv, Any] {
  def sayHello(
      request: HelloRequest
  ): ZIO[zio.ZEnv, Status, HelloReply] =
    putStrLn(s"Got request: $request") *>
      ZIO.succeed(HelloReply(null))
}
```
Start the server and call the client HelloWorldClient.

**Comment by fokot** [comment]
I tried to catch it in `CallDriver.unaryInputCallDriver` like this
```scala
run = (
  call.request(2) *>
  completed.await *>
  call.sendHeaders(new Metadata) *>
  request.await >>= (r => writeResponse(r).tapCause(c => UIO(println("write: " + c.toString))))
).onExit(ex => call.close(CallDriver.exitToStatus(ex), new Metadata).ignore)
  .tap(_ => UIO(println("done")))
  .tapCause(c => UIO(println("cause: " + c.toString)))
  .ignore
  .race(cancelled.await)
```
but I got just done. No error from `writeResponse` neither from full effect.

**Comment by thesamet** [comment]
ScalaPB libraries, in a similar way to other Scala libraries, do not perform null check at entry points. It's the user's responsibility to not pass nulls in.
