### ISSUE TITLE
using exotic scheme as URI

### ISSUE THREAD

**Issue by ubourdon** [scalapb/zio-grpc#187]
Hi,

I try to make a grpc client for a eventstore db using zio-grpc, and the scheme to use to connect the db is `esdb://` but when i use it client throw an error `cannot find a NameResolver for esdb://xxx`.

THere is a way to handle this kind of scheme ?

I use `ManagedChannelBuilder.forTarget(s"esdb://$host:$port")` to init the managed builder.

ManagedChannelBuilder.forAddress dont allow me to specify a specific scheme.

**Comment by thesamet** [comment]
Hi @ubourdon , this scheme is not known to grpc-java.  If it's just a grpc service behind `$host:$port` then maybe just strip out the scheme?

**Comment by ubourdon** [comment]
Hi. Thx for your answer.
Seems esdb:// scheme is mandatory for connect the db.

They make an java client for their db and use this scheme cf. https://github.com/EventStore/EventStoreDB-Client-Java/blob/trunk/db-client-java/src/test/java/testcontainers/module/EventStoreTestDBContainer.java#L64

I think they use grpc-java too no ? Do you know how to do same ?

**Comment by thesamet** [comment]
I am not familiar with EventStoreDB. I suggest asking their devs whether it is possible to connect a service from a standard grpc client. If it's a standard grpc service, you can also try connecting to it using a command-line tool such as https://github.com/fullstorydev/grpcurl

**Comment by ubourdon** [comment]
Thx for your help.
At the opposite of i write before, seems esdb scheme is not mandatory.
The tool you  link to me will be very useful.
Thx again.
