### ISSUE TITLE
Publish codegen for scala 2.13?

### ISSUE THREAD

**Issue by virusdave** [scalapb/zio-grpc#213]
Hello,

It looks like you've stopped publishing libraries for scala 2.13.  Is there a reason?  Can you publish the recent 0.4.x releases for 2.13?

Thanks!

**Comment by thesamet** [comment]
Hi Dave, we're still publishing for 2.13, here are the artifacts: https://repo1.maven.org/maven2/com/thesamet/scalapb/zio-grpc/zio-grpc-core_2.13/0.4.3/

The codegen itself is published only for 2.12 since it's needed for sbt (which is based on 2.12), but that shouldn't impact you as a user.

**Comment by virusdave** [comment]
I was just about to note that i refer specifically to `zio-grpc-codegen`, but you beat me to it.
It actually does impact me, since I'm using Bazel not SBT.

**Comment by virusdave** [comment]
To clarify, I'd like to use the codegen as one of the generators for protobufs, which should work just fine (with a bit of config magic) assuming a 2.13 version is published (since our codebase is a 2.13 scala tree)

**Comment by thesamet** [comment]
codegen is now published for all versions of Scala.
