### ISSUE TITLE
ZTransform fails to infer types

### ISSUE THREAD

**Issue by frekw** [scalapb/zio-grpc#217]
Hi!

Adding the issues [from gitter](https://gitter.im/ScalaPB/community?at=604094a4d2619a4f2e20422a) that I ran into.

Basically, `ZTransform` fails to infer the types even for simple transformations.

[This gist](https://gist.github.com/frekw/8d671592ca202256835db8a82692ee24), more or less extracted from the guides, fails to compile with

```
[error] src/work/zio-grpc/examples/src/main/scala/zio_grpc/examples/helloworld/HelloWorldServer.scala:36:56: could not find implicit value for parameter b: scalapb.zio_grpc.ZBindableService[zio.ZEnv,io.grpc.examples.helloworld.helloworld.ZioHelloworld.ZGreeter[zio.ZEnv with Any with zio.Has[scalapb.zio_grpc.RequestContext],zio.ZEnv with Any with zio.Has[scalapb.zio_grpc.RequestContext]]]
[error]   def services: ServiceList[zio.ZEnv] = ServiceList.add(GreeterImpl.transform(new Logging))
```

However, adding type annotations to the `transform` call solves this:

```scala
val svc = GreeterImpl.transform[ZEnv, Any](new Logging)
def services = ServiceList.add(svc)
```

For real world apps, this becomes slightly more complex since the environment requirements might be more complex:

```scala
val  decorated = MyService
  .transform[MyService.Env with Has[Metrics], Has[RequestContext]](
      new api.grpc.middleware.metrics.Duration[MyService.Env] andThen
      new api.grpc.middleware.metrics.Errors[MyService.Env with Has[Metrics] with Has[RequestContext]] andThen
      new api.grpc.middleware.LoggingTransform[MyService.Env with Has[Metrics] with as[RequestContext]            ]
        )
```

in which case you'll also need to combine the different parts of the environment manually between each `andThen` call.

I would guess that this is due to the fact that `ZTransform` is invariant w.r.t `R`.

**Comment by thesamet** [comment]
`ZTransform` and `Transform` have been simplified in 0.6.0-rc1. PTAL!

**Comment by frekw** [comment]
Yeah I just saw, will dig into them as soon as an RC is available! Will this make the context contravariant? That'd be awesome!

**Comment by thesamet** [comment]
rc1 is on maven now. And yes, context is contravariant. Since this is an old issue, there have been bunch of changes: 0.6.0 is targetting ZIO2. The service no longer has an `R` type parameter (pass dependency via constructors), and the context is given through a parameter to each method, not the environment.

**Comment by frekw** [comment]
Sounds like great changes all around! Can't wait to give it a spin this week!
