### ISSUE TITLE
Failing RPCs can have their status replaced by CANCLED

### ISSUE THREAD

**Issue by Marc-Ducret** [scalapb/zio-grpc#224]
* In [CallDriver.scala L28](https://github.com/scalapb/zio-grpc/blob/1d40515d4fae3210bbfc8ed81f6a6df0eab41c54/core/jvm/src/main/scala/scalapb/zio_grpc/server/CallDriver.scala#L28): the status is set to `CANCELED` whenever `cause.interrupted` is true.

* In this simple code sniped, we have an effect that fails with an error **and** `cause.interrupted` being true:
```scala
import zio._
import zio.duration._

object TestForeachPar extends App {

  override def run(args: List[String]): URIO[ZEnv, ExitCode] =
    ZIO
      .foreachParN_(128)(List.range(0, 16))(i =>
        for {
          delay <- zio.random.nextIntBetween(1000, 2000)
          _ <- ZIO.fail(s"i=$i").delay(delay.milliseconds)
        } yield ()
      )
      .onExit {
        case Exit.Success(_) => ZIO.effectTotal(println(s"success"))
        case Exit.Failure(cause) =>
          ZIO.effectTotal(
            println(
              s"interrupted: ${cause.interrupted}, died: ${cause.died}, failed: ${cause.failed}, failure: ${cause.failureOption}"
            )
          )
      }
      .ignore
      .exitCode

}
```
output:
```
interrupted: true, died: false, failed: true, failure: Some(i=15)
```

It is especially problematic for us as our gRPC clients treat CANCELED statuses as retriable.

**Simple fix:** replace `cause.interrupted` with `cause.interruptedOnly` in CallDriver.scala

**Comment by thesamet** [comment]
Hi @Marc-Ducret - thanks for reporting. Will you be able to put together a PR and include the test case as well to prevent regressions?

**Comment by Marc-Ducret** [comment]
Hi @thesamet, sure.
Here is the PR: https://github.com/scalapb/zio-grpc/pull/225
