### ISSUE TITLE
Support Scala 3

### ISSUE THREAD

**Issue by thesamet** [scalapb/zio-grpc#250]
The code in master currently compiles for Scala 3, however the tests fail in runtime. 

To run the tests in sbt:
```
e2eJVM3_0_0_RC3/test
```

You'll notice that TestServiceSpec gets stuck. By commenting out some tests I was also able to get an exception related pertaining to a "defect in `zio.Has`".

**Comment by octavz** [comment]
Hi I believe these are related, https://github.com/zio/izumi-reflect/issues/103, tried to look a bit but couldn't figure it out yet.

**Comment by adamstarlight** [comment]
Are there any news?

**Comment by thesamet** [comment]
No, the root cause isn't identified yet. It would be great if someone can look into it.

**Comment by ultram4rine** [comment]
Hi, is the problem still there? I ran `e2eJVM3/test` and all tests seem to pass.

**Comment by thesamet** [comment]
Scala 3 is now supported.
