### ISSUE TITLE
Server layer requires needs implicits – current repo example (ExampleServer) doesn't work

### ISSUE THREAD

**Issue by Nickersoft** [scalapb/zio-grpc#257]
I apologize for opening another issue so quickly after closing my last, but poking around the examples in the code (and attempting to work on my own server), I noticed that ServerLayer (or the legacy Server) cannot be used without the use of an implicit ZBindableService. 

No matter which implicits are imported I can't seem to get this message to go away: 

![image](https://user-images.githubusercontent.com/2104129/118068346-0dcd0a00-b357-11eb-9c31-7e5147a30766.png)

I noticed this error was also mentioned in #217, but I'm not sure if it is the same issue. I'm curious how the implicit is supposed to be passed or what value is expected here.

**Comment by thesamet** [comment]
IntelliJ error reporting can sometimes be incorrect. Can you check if there is really a compilation error by trying to compile your project with `sbt compile`?  If there is, can you put together a sample project demonstrating the failure?

**Comment by Nickersoft** [comment]
I can confirm the entire ExampleServer doesn't seem to compile.. `sbt` seems to only run the code in `src`, so I forked this repo and moved the `server` folder inside `src` and changed the package: https://github.com/Nickersoft/zio-grpc/tree/master/examples/src/main/scala/zio_grpc/examples/server.

Running `sbt` produced:

```
[info] welcome to sbt 1.5.2 (N/A Java 15.0.2)
[info] loading global plugins from /Users/tnickerson/.sbt/1.0/plugins
[info] loading settings for project examples-build from plugins.sbt ...
[info] loading project definition from /Users/tnickerson/base/zio-grpc/examples/project
[info] loading settings for project examples from build.sbt ...
[info] set current project to examples (in build file:/Users/tnickerson/base/zio-grpc/examples/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] compiling 2 Scala sources to /Users/tnickerson/base/zio-grpc/examples/target/scala-2.13/classes ...
[error] /Users/tnickerson/base/zio-grpc/examples/src/main/scala/zio_grpc/examples/server/ExampleServer.scala:37:10: value scheduleElements is not a member of zio.stream.ZStream[Any,Nothing,examples.greeter.Point]
[error] possible cause: maybe a semicolon is missing before `value scheduleElements`?
[error]         .scheduleElements(Schedule.spaced(1000.millis))
[error]          ^
[error] /Users/tnickerson/base/zio-grpc/examples/src/main/scala/zio_grpc/examples/server/ExampleServer.scala:64:64: type mismatch;
[error]  found   : zio.ZLayer[zio.Has[examples.greeter.ZioGreeter.Greeter],Throwable,scalapb.zio_grpc.Server]
[error]     (which expands to)  zio.ZLayer[zio.Has[examples.greeter.ZioGreeter.ZGreeter[Any,Any]],Throwable,zio.Has[scalapb.zio_grpc.Server.Service]]
[error]  required: zio.ZLayer[zio_grpc.examples.GreeterService.GreeterService,Nothing,scalapb.zio_grpc.Server]
[error]     (which expands to)  zio.ZLayer[zio.Has[examples.greeter.ZioGreeter.ZGreeter[Any,Any]],Nothing,zio.Has[scalapb.zio_grpc.Server.Service]]
[error]     Clock.live >>> GreeterService.live >>> Server.live[Greeter](
[error]                                                                ^
[error] /Users/tnickerson/base/zio-grpc/examples/src/main/scala/zio_grpc/examples/server/ExampleServerWithMetadata.scala:57:43: type mismatch;
[error]  found   : examples.greeter.ZioGreeter.ZGreeter[Any,zio.Has[scalapb.zio_grpc.RequestContext]]
[error]  required: examples.greeter.ZioGreeter.Greeter
[error]     (which expands to)  examples.greeter.ZioGreeter.ZGreeter[Any,Any]
[error]       new LiveService(c).transformContextM(findUser(_))
[error]                                           ^
[error] /Users/tnickerson/base/zio-grpc/examples/src/main/scala/zio_grpc/examples/server/ExampleServerWithMetadata.scala:70:21: type mismatch;
[error]  found   : zio.ZLayer[zio.Has[examples.greeter.ZioGreeter.Greeter],Throwable,scalapb.zio_grpc.Server]
[error]     (which expands to)  zio.ZLayer[zio.Has[examples.greeter.ZioGreeter.ZGreeter[Any,Any]],Throwable,zio.Has[scalapb.zio_grpc.Server.Service]]
[error]  required: zio.ZLayer[zio.Has[examples.greeter.ZioGreeter.Greeter],Nothing,scalapb.zio_grpc.Server]
[error]     (which expands to)  zio.ZLayer[zio.Has[examples.greeter.ZioGreeter.ZGreeter[Any,Any]],Nothing,zio.Has[scalapb.zio_grpc.Server.Service]]
[error]       .live[Greeter](
[error]                     ^
[error] four errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 3 s, completed May 12, 2021, 10:59:11 PM
```

As far as the implicit error, I can confirm I received an error in IntelliJ for the example code and for my own code, and compiling my own code definitely shows the error during compilation. My guess is the only reason it's not in the above stack trace is the compiler hasn't hit that part of the code yet, and that error might pop up once the above errors are fixed.

**Comment by thesamet** [comment]
You are right, thanks for reporting this! It looks like the `build.sbt` we currently have in the `examples` directory got messed up at some point. As a result, some of the example code doesn't get compiled and might no longer compile. I'll look into it and get that fixed soon. However, the following files still contain server code that gets compiled on CI: `src/main/scala/zio_grpc/examples/helloworld/HelloWorldServer.scala` and `src/main/scala/zio_grpc/examples/routeguide/RouteGuideServer.scala`. 
Can you take a look and see if these are useful examples?

**Comment by Nickersoft** [comment]
That would be very helpful :) I was mostly interested in ExampleServer because it seemed to have a concrete example of how to use a service that has other module dependencies. RouteGuide technically has dependencies, but they aren't the kind that are provided via a layer (just constructor-based value deps). I looked at the [docs](https://scalapb.github.io/zio-grpc/docs/context), but it seems to mostly focus on depending on another service to transform a request into the context the service needs to run. In my case, my service requirements extend what's provided in ZEnv, which is a case ExampleServer seemed to explore.

**Comment by thesamet** [comment]
I updated the examples to latest version of ZIO and ZIO-gRPC such that they all compile. The source you were looking at is now in `examples/fullapp`. Can you take a look?

**Comment by Nickersoft** [comment]
Looks good! Not sure what did it, but from the looks of things the implicit error has gone away. I should be able to work with this. Thanks so much!
