### ISSUE TITLE
Support ZIO 2.0

### ISSUE THREAD

**Issue by devsprint** [scalapb/zio-grpc#299]
ZIO is evolving ... ZIO 2.0 support will be great.

**Comment by thesamet** [comment]
Took a stab at it. We currently have all the tests working except of one related to RPC cancellation. There are plenty of compile-time warning on deprecations that need to be cleaned up as well. If anyone would like to take it from here - it would be appreciated!

**Comment by devsprint** [comment]
@thesamet I will look over it and contribute during this week-end. Thank you

**Comment by gavares** [comment]
My MR fixes the failing tests and deprecations: #311

**Comment by carbonshow** [comment]
the `Has` data type has been removed since ZIO 2.0.0-M6, see [ZIO release notes](https://github.com/zio/zio/releases/tag/v2.0.0-M6).

@gavares could you update grpc with the change?

**Comment by ya-goodfella** [comment]
Hi @thesamet, 

Appreciation of all the wonderful effort you do on this track. :) 

I've tried to migrate my project to zio 2.0.0-RC5 and unfortunately latest head of zio2 branch generates code that is incompatible with RC5. 

Have you tried to look into the latest zio RC? Maybe you may drop some tips for me how to solve generated code incompatibilities effectively, so maybe I would be able to bring such PR by myself? :) 

Cheers.

**Comment by thesamet** [comment]
Hi @ya-goodfella , there are end-to-end tests within this repo that show up as `eveJVM2_13` in sbt. Running these tests generates code for the e2e project. The process for solving the incompatibilities is a matter of making changes to the generator code and running the e2e tests through SBT.

**Comment by ashwinbhaskar** [comment]
@ya-goodfella `zio2`'s head uses `ZIO 2.0.0-RC1`

**Comment by Nickersoft** [comment]
Now that https://github.com/scalapb/zio-grpc/pull/400 is landed, can this issue be closed? It looks like there may still be some lingering issues, however (e.g. #410).
