### ISSUE TITLE
Metadata support

### ISSUE THREAD

**Issue by frekw** [scalapb/zio-grpc#30]
Hi!

Is support for metadata (authorization headers in my case) currently supported? If it is, I can't seem to figure out how.

**Comment by thesamet** [comment]
Hi @frekw, it's currently unsupported. On the server side, are you looking to get it as a parameter to your handler or to intercept it before the call to your handler?

**Comment by frekw** [comment]
Hi @thesamet!

I'm primarily looking to get it as a parameter to the handler.

Having support for interceptors would definitely be useful as well, but I guess that could be quite easily worked around in userland!

**Comment by frekw** [comment]
I tried to give it a go by tweaking the code generation to produce two separate traits, one for the server which accepts `io.grpc.Metadata` as a second parameter and one for the client that I kept as-is.

Then I got kind of stuck how to actually thread the metadata through via the `ZServerCallHandler.*CallHandler`-methods, most likely because I don't know the internals well enough. I think there's a need to introduce another layer of wrapping to pass down the metadata as arguments before calling `call.request()` in the `ZServerCall`, but I'm probably mostly guessing at this point.

**Comment by frekw** [comment]
Awesome, I'll give it a go straight away!

**Comment by andersmartini** [comment]
> I added a new `MyServer.WithContext[Context]` trait when all the handlers get a context parameter as a second parameter. Those services can be bound to a server along with a function that transforms `Metadata` into `Context`. `Context` can be any domain-specific object for your app. I put together a few examples here: https://github.com/scalapb/zio-grpc/tree/master/examples/src/main

that link is a 404, can the examples be found somewhere else these days?
