### ISSUE TITLE
Highlight error on .usePlaintext() for gRPC client

### ISSUE THREAD

**Issue by nsadeh** [scalapb/zio-grpc#314]
Description:

I lifted the following code out of the example: https://scalapb.github.io/zio-grpc/docs/basics#creating-the-client

```scala
val demoService: Layer[Throwable, DemoServiceClient] = DemoServiceClient.live(
    ZManagedChannel(
      ManagedChannelBuilder.forAddress("localhost", 8080).usePlaintext()
    )
  )
```

because of the type signature of .usePlaintext(), I get `Cannot resolve overloaded method 'ZManagedChannel'` as a syntax highlight for an error. However, SBT knows how to compile it.

Not sure if this should go here or as an IntelliJ bug, but was wondering if you knew a way to make this not throw a syntax highlight as it's bad practice to accumulate false positives in the codebase.

**Comment by thesamet** [comment]
Hey @nsadeh , this appears like an IntelliJ bug and should be reported in their tracker - I am not sure there's anything we can do within this repo or of a way to suppress it.
