### ISSUE TITLE
SafeMetadata inconvenient usage to get info from raw metadata, always forced to be wrapped with Effect or unsafeRun

### ISSUE THREAD

**Issue by kuzkdmy** [scalapb/zio-grpc#356]
Having existing contract of SafeMetadata, it is not comfortable for clients that want to get something from metadata and make this a part of ZIO env for generated server

It looks that contract method with unsafeMetadata or getMetadataState can be a good solution 

Where it is not comfortable:
trait Z.....GENERATED......Service[-R, -Context]
When you wish this -Context to be some custom class, example Ctx that can be constructed from metadata
You have to write CanBind[Ctx]
![image](https://user-images.githubusercontent.com/15995100/151138156-f15c1f71-b291-4bfb-9026-2bcaf18f396c.png)

Oritinal code of SafeMetadata
```
final class SafeMetadata private (
    private val sem: Semaphore,
    private[zio_grpc] val metadata: Metadata
) {
  def get[T](key: Metadata.Key[T]): UIO[Option[T]] =
    wrap(m => Option(m.get(key)))

  def put[T](key: Metadata.Key[T], value: T): UIO[Unit] =
    wrap(_.put(key, value))

  def remove[T](key: Metadata.Key[T], value: T): UIO[Boolean] =
    wrap(_.remove(key, value))

  /** Creates an effect from a total side-effecting function of metadata */
  def wrap[A](f: Metadata => A): UIO[A] =
    sem.withPermit(ZIO.effectTotal(f(metadata)))
}

```

**Comment by thesamet** [comment]
Thanks for reporting. Please check out [this doc](https://scalapb.github.io/zio-grpc/docs/context#context-transformations). You can write a service where the context class is `Ctx2`, and use `transformContextM` to convert it to a service that has `RequestContext` as context so you don't have have to write a `CanBind` yourself. The next example on that page is how to effectfully resolve a user from Metadata. Please let me know if this covers your use case, and also any suggestion on how to make this information more discoverable will be welcome.

**Comment by justcoon** [comment]
@thesamet  is there way how to get all  keys ?
something similar to

```
io.grpc.Metadata.keys()
```
?

**Comment by thesamet** [comment]
You can call any `Metadata` method through `wrap`: https://github.com/scalapb/zio-grpc/blob/0f241c21e6df755e01f9711a6a5030cc4a44e999/core/src/main/scala/scalapb/zio_grpc/SafeMetadata.scala#L22: `safeMetadata.wrap(_.keys)`

**Comment by justcoon** [comment]
@thesamet thank you very much for hint
