### ISSUE TITLE
Quickstart fails to run on a M1 Mac

### ISSUE THREAD

**Issue by GMadorell** [scalapb/zio-grpc#364]
* OS: macOS Monterey 12.2 on a Apple M1 Pro chip.

Running over Quickstart (https://scalapb.github.io/zio-grpc/docs/quickstart), all steps until the following one work perfectly:

```
sbt "runMain zio_grpc.examples.helloworld.HelloWorldServer"
```

Running this one fails with: 
```
[error] (protocExecutable) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.15.6/protoc-3.15.6-osx-aarch_64.exe: not found: https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.15.6/protoc-3.15.6-osx-aarch_64.exe
```

I've done some research and came across this one: https://github.com/protocolbuffers/protobuf/issues/8062. Seems like "oldish" versions of protobuf are not compiled for M1 chips.

With this, my best guess is that updating the version would fix this, but I really have not much of an idea if it's 100% true.

I Tried doing it myself but it was a bit overwhelming tbh.

**Comment by thesamet** [comment]
Thanks for reporting! I'll look into this in more detail, but I believe that updating `project/plugins.sbt` to the latest version of sbt-protoc (1.0.6) should resolve this.
