### ISSUE TITLE
Support for flatPackage=true

### ISSUE THREAD

**Issue by ghostdogpr** [scalapb/zio-grpc#37]
It seems that zio-grpc ignores the flatPackage setting so it generates code that doesn't compile when this is `true` (the data is expected to be in their own packages). 

Is there a way to make this work in flat mode?

**Comment by thesamet** [comment]
Hi @ghostdogpr ,
Currently, the only way to do it is to specify `flat_package: true` as a [package-scoped option](https://scalapb.github.io/customizations.html#package-scoped-options) so the same set of options are picked up by both ScalaPB and zio-grpc.

**Comment by ghostdogpr** [comment]
Oh, that's great, I thought that wasn't supported. Thanks!

**Comment by tnielens** [comment]
Could this one be reopened? It'd be convenient to define this globally 🙏 .

**Comment by tnielens** [comment]
Oh I'm reading about https://scalapb.github.io/docs/faq#why-a-certain-customization-is-not-available-as-a-global-generator-parameter. Might be an option you don't want to support.

**Comment by thesamet** [comment]
This can be accomplished globally by just adding a file to your project.

**Comment by tnielens** [comment]
You mean with package-scoped options on the top-most package?

**Comment by thesamet** [comment]
Yes. Applying settings globally proved to caused problems since it's common to import third-party protos which already have code generated under incompatible settings.
