### ISSUE TITLE
Multiple services in the same server

### ISSUE THREAD

**Issue by ghostdogpr** [scalapb/zio-grpc#38]
Is it possible to create a single server with multiple services?

The example project only shows a single service, and I'm failing to find how to use several. `Server.live` doesn't seem usable if I have `Has[FooService] with Has[BarService]`. It looks as if we need an intermediate structure to combine multiple services before we turn it into a server. But maybe I missed something. Any idea how to tackle that?

Thanks!

**Comment by thesamet** [comment]
I added variants of `Server.live` and `Server.managed` that work for two and three services. It should be possible to generalize further. How many services do you expect to have?

**Comment by ghostdogpr** [comment]
I have 19 currently 😅

**Comment by thesamet** [comment]
On the latest snapshot, you can try:

```
Server.managed(ServerBuilder.forPort(8080),
  UIO.collectAll(
    ZBindableServer.serviceDefinition(service1),
    ZBindableServer.serviceDefinition(service2),
    ...,
    ZBindableServer.serviceDefinition(service19)
  )
)
```

Please let me know if it does the job.

**Comment by ghostdogpr** [comment]
Yeah, just tried it and it works perfectly. Thanks!
