### ISSUE TITLE
How to use `zio-grpc` in maven?

### ISSUE THREAD

**Issue by jxnu-liguobin** [scalapb/zio-grpc#388]
I didn't find the plugin, or how to implement a new maven plugin ?

**Comment by thesamet** [comment]
Hi @jxnu-liguobin , we publish an executable version of the plugin here: https://mvnrepository.com/artifact/com.thesamet.scalapb.zio-grpc/protoc-gen-zio/0.5.1

I haven't tested it, but If you follow the example in this file and add a file line the one highlighted https://github.com/thesamet/scalapb-maven-example/blob/87721bc939a2440ef0bc9802df4863799e15de09/pom.xml#L144 adapted for the linked plugin above, it should work. I would appreciate if you can report back your results here for other users to benefit.

**Comment by jxnu-liguobin** [comment]
Thank you for your reply. I'd like to try it.

**Comment by jxnu-liguobin** [comment]
@thesamet Compile failed: "error: class Any needs to be a trait to be mixed in",
But I have added dependency "scalapb-runtime-grpc"

**Comment by jxnu-liguobin** [comment]
Because the scalapb protoc version does not match the scalapb runtime version
