### ISSUE TITLE
Compile failed when run in github ci

### ISSUE THREAD

**Issue by jxnu-liguobin** [scalapb/zio-grpc#389]
![image](https://user-images.githubusercontent.com/29496873/164583485-af15c3ac-aa92-4235-9a30-c36ca5b31a70.png)

Could someone know how to resolve it ？ Maybe charset？ Thank you.

BTW It's work on Mac osx。

More information about error ：https://github.com/bitlap/bitlap/runs/6115339544?check_suite_focus=true

**Comment by thesamet** [comment]
It looks like you're passing binary files as proto files:
```
Error:  /home/runner/work/bitlap/bitlap/bitlap-network/src/main/protobuf/service.proto [0:0]: /tmp/protoc1259948753581453796.exe: 1: �O: not found
Error:  /home/runner/work/bitlap/bitlap/bitlap-network/src/main/protobuf/service.proto [0:0]: /tmp/protoc1259948753581453796.exe: 1: P�L: not found
```
so protoc (the protoc compiler) fails.

**Comment by jxnu-liguobin** [comment]
> It looks like you're passing binary files as proto files:
> 
> ```
> 
> Error:  /home/runner/work/bitlap/bitlap/bitlap-network/src/main/protobuf/service.proto [0:0]: /tmp/protoc1259948753581453796.exe: 1: �O: not found
> 
> Error:  /home/runner/work/bitlap/bitlap/bitlap-network/src/main/protobuf/service.proto [0:0]: /tmp/protoc1259948753581453796.exe: 1: P�L: not found
> 
> ```
> 
> so protoc (the protoc compiler) fails.
> 
> 

Is the file stored in the wrong format?

**Comment by thesamet** [comment]
Hi @jxnu-liguobin , please take the time to do perform some initial investigation before filing issues and asking for help. Github issues are meant to report bugs. To understand what the protobuf compiler does, you can start by following one of these tutorials: https://scalapb.github.io/docs/getting-started

**Comment by thesamet** [comment]
I took a second look at the project and the mentioned file does seem to be a proto file, so there's something else going on. I suggest trying to investigate further by minimizing the change you are introducing to the repo.

**Comment by jxnu-liguobin** [comment]
Solved, because a osx Google protoc is introduced into POM。
