### ISSUE TITLE
Context support

### ISSUE THREAD

**Issue by ghostdogpr** [scalapb/zio-grpc#39]
Calling `GrpcContext.key("my-key").get()` triggers a `NullPointerException` because of an underlying call to `Context.current()` that returns null. It seems the Java library is using `ThreadLocal` to store the context, and while the interceptors are running in a dedicated thread managed by the Java library, our handlers are running in threads from the ZIO thread pool. 

Any idea on how to deal with this?

**Comment by thesamet** [comment]
I think that getting grpc-java's Context to work is going to be tricky given the way threads work in zoo. Can you share more about what you're trying to do? Are you familiar with the recently added `WithContext[A]` trait? Maybe `FiberRef[A]` can be utilized?

**Comment by ghostdogpr** [comment]
Sure, the use case is pretty simple. I'm migrating some code from ScalaPB/Future to zio-grpc. The old code was using interceptors to extract some data from headers and save them in the Context, then reading it from the handler's code.

I thought of `FiberRef` but the interceptor is called before `unsafeRun`, even before there is any fiber so I didn't really see how to use it. I didn't know about `WithContext`, would that help here? Checking the examples now.

**Comment by ghostdogpr** [comment]
OK, I think I understand. The interceptor gives me the input metadata and let me modify, so I can add my extra stuff in, and then using the `WithContext` variant I can read the metadata (or whatever object I mapped it to). That should do it, thanks.

**Comment by thesamet** [comment]
Yes, the relevant example is https://github.com/scalapb/zio-grpc/blob/beeaf3a725ac14f56f4d559e8f75d9625c0acd0e/examples/src/main/scala/examples/ExampleServerWithMetadata.scala#L55 . The transformation is effectful, so you can also decide to fail the request if the metadata doesn't validate.
