### ISSUE TITLE
Support Graceful Shutdown for Server

### ISSUE THREAD

**Issue by Gregory-Berkman-Imprivata** [scalapb/zio-grpc#399]
The zio-grpc wrapper for `io.grpc.Server` does not allow for graceful shutdown. 

The method in `scalapb.zio_grpc.ServerImpl`: 
`def shutdown: Task[Unit] = ZIO.effect(underlying.shutdown()).unit` 
calls the underlying shutdown which returns before preexisting calls have finished. The underlying Server does have an `awaitTermination` which blocks until all of the preexisting calls have finished (after `shutdown` is called) but this is not exposed. 

A simple fix could be to update `toManaged`. Here is a simple example for adding graceful shutdown: 
`def toManaged: ZManaged[Any, Throwable, Service] = start.as(this).toManaged(_ => (this.shutdown *> ZIO.effect(awaitTermination())).ignore)`

A more sophisticated solution should take a timeout as some sort of parameter.

**Comment by thesamet** [comment]
Thanks for reporting and suggesting the fix in `toManaged`. I assume you're not too far from sending a PR :) If possible, it would be great to get two PRs to target both master branch for ZIO 2 and 0.5.x for ZIO 1. As a heads up the ZIO 2 branch doesn't have `Managed`.

**Comment by thesamet** [comment]
Solved in #416.
