### ISSUE TITLE
ZIO 2.0 (zio.Runtime$unsafeRun())

### ISSUE THREAD

**Issue by Vlad1Badilovskii** [scalapb/zio-grpc#410]
Hallo, there are some braking changes was made by ZIO 2.0. They do not have unsafeRun() method in Runtime anymore.  
`io.Runtime.unsafeRun(Lzio/ZIO;Ljava/lang/Object;)Ljava/lang/Object;
	at scalapb.zio_grpc.client.UnaryClientCallListener.onClose(UnaryClientCallListener.scala:52)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:468)`

**Comment by thesamet** [comment]
I believe this will be resolved with a new releae of zio-grpc that is compiled with 2.0.0. In the meantime, can you try the snapshot version `0.0.0+1-d7f1552a-SNAPSHOT` and report if it works?

**Comment by ghostdogpr** [comment]
@thesamet is it possible to make a real release? I can't make the code generation plugin using a snapshot 🤔

**Comment by Vlad1Badilovskii** [comment]
> I believe this will be resolved with a new releae of zio-grpc that is compiled with 2.0.0. In the meantime, can you try the snapshot version `0.0.0+1-d7f1552a-SNAPSHOT` and report if it works?

Sorry for so long. On local looks good, but due to security restrictions of my project can't use snapshot

**Comment by Killjoyer** [comment]
Hello. When approximately there will be a zio 2.0.0 release? I see tag `0.6.0-test4` on github, but there is no such release on [maven](https://repo1.maven.org/maven2/com/thesamet/scalapb/zio-grpc/).

**Comment by Vlad1Badilovskii** [comment]
> Hello. When approximately there will be a zio 2.0.0 release? I see tag `0.6.0-test4` on github, but there is no such release on [maven](https://repo1.maven.org/maven2/com/thesamet/scalapb/zio-grpc/).

+1

**Comment by thesamet** [comment]
Love the anticipation here :) I fixed the build (our pgp key had expired) and 0.6.0-test4 should be on maven shortly.

**Comment by shonfeder** [comment]
Thanks or all your excellent work, @thesamet!
