### ISSUE TITLE
Test against the latest ZIO snapshot

### ISSUE THREAD

**Issue by iravid** [scalapb/zio-grpc#46]
Hi @thesamet, we just merged a big refactor to ZStream that embeds chunks on all streams.

 Would be great if you could test zio-grpc against the latest snapshot and see if any issues pop up.

**Comment by thesamet** [comment]
Tests pass with latest snapshot at ae9cf3a. Seems like there was a signature change in the type parameters of brackExit for ZStreams which caused a compilation error. It seems like this was actually an improvement in type inference, so removing the explicit type parameters fixed the compilation error.

**Comment by iravid** [comment]
Thanks!
