### ISSUE TITLE
After adding context to ZIO gRPC service missing implicit ZBindableService error is thrown

### ISSUE THREAD

**Issue by TomasMonkevic** [scalapb/zio-grpc#460]
Hey, I'm trying to make a gRPC service that accesses data from metadata however I get this compiler error:

`could not find implicit value for parameter bs: scalapb.zio_grpc.ZBindableService`

You can check the project [here](https://github.com/TomasMonkevic/Plurpy/blob/get-auth-context-from-metadata/plurpy-backend/src/main/scala/Main.scala)

**Comment by thesamet** [comment]
It looks like currently obtaining a ZBindableService can only happen after you resolved all the environment dependencies for your `ZService[R,C]`, that is when you have `ZService[Any,C]`. I've sent a PR to your repo to show how this can be done in this case. I will leave the issue open to ensure this is either resolved with better error, fixed or documented

**Comment by TomasMonkevic** [comment]
Thank you so much for the help :heart:
