### ISSUE TITLE
[v0.6.0-test8] How do I create a serverLayer with multiple services?

### ISSUE THREAD

**Issue by oscar-broman** [scalapb/zio-grpc#471]
Hi

I've been using the test version for a while now and I saw that there are a few new versions. I attempted to upgrade but I'm struggling to understand how to construct my server when I have more than one service.

In `v0.6.0-test4` I'm doing as shown below.

How do I port this code to `v0.6.0-test8`?

```scala
import com.myproject.schema.ZioTest.{ZGrpcService1, ZGrpcService2} // generated by the SBT plugin

trait MyService1 {} // internal service
trait MyService2 {} // internal service
trait MyService3 {} // internal service
object MyService1Impl extends MyService1 { val layer: ZLayer[Any, Nothing, MyService1] = ??? }
object MyService2Impl extends MyService2 { val layer: ZLayer[Any, Nothing, MyService2] = ??? }
object MyService3Impl extends MyService3 { val layer: ZLayer[Any, Nothing, MyService3] = ??? }

object GrpcService1Impl extends ZGrpcService1[MyService1 & MyService2 & MyService3, Any] {
  // implement abstract methods
}

object GrpcService2Impl extends ZGrpcService2[Any, Any] {
  // implement abstract methods
}

object MyServer extends ZIOAppDefault {
  def port: Int = 9000

  def builder = ServerBuilder.forPort(port).addService(ProtoReflectionService.newInstance())

  def serverLayer: ZLayer[MyService1 & MyService2 & MyService3, Throwable, Service] = {
    ServerLayer.fromServices(builder, GrpcService1Impl, GrpcService2Impl)
  }

  val myAppLogic = ZLayer.make[Server](
    MyService1Impl.layer,
    MyService2Impl.layer,
    MyService3Impl.layer,
    serverLayer,
  )

  def run = (myAppLogic.build *> ZIO.never).exitCode
}
```

**Comment by thesamet** [comment]
Hi Oskar, have you looked into [implementing a service with dependencies](https://scalapb.github.io/zio-grpc/docs/next/context/#implementing-a-service-with-dependencies)? In `test8` one of the breaking changes is that the dependencies should be passed through the constructor, not through the environment.

**Comment by thesamet** [comment]
In the commit above I added an example and improved the docs for using layers. Please take a look at https://github.com/scalapb/zio-grpc/blob/44c08d432c440f41edee767a4e820ee06d754726/examples/helloworld/src/main/scala/zio_grpc/examples/helloworld/MultipleServices.scala,  the caveat is that you can't use ServerMain.
