### ISSUE TITLE
Scala 3 version for Scala js?

### ISSUE THREAD

**Issue by sergeda** [scalapb/zio-grpc#485]
I ran into an issue when changed version of Scala to 3.2.2. I got this error:
`Error downloading com.thesamet.scalapb.zio-grpc:zio-grpc-core_sjs1_3:0.6.0-rc2`
I tried to add `("com.thesamet.scalapb.zio-grpc" %% "zio-grpc-core" % zioGrpcVersion).cross(CrossVersion.for3Use2_13),` as a dependency to make it work but no luck. How this can be fixed?

**Comment by thesamet** [comment]
Currently, zio-grpc doesn't have Scala.js support over Scala 3.x due to what appears to be a Scala compiler or Scala.js bug. I've just reached out over discord to see how we can resolve this: https://discord.com/channels/632150470000902164/635668814956068864/1081651892108668938

**Comment by thesamet** [comment]
Turns out it was a build issue here, fixed in b7272607. Please try `v0.6.0-rc3`
