### ISSUE TITLE
Can't use Metadata in webapp client

### ISSUE THREAD

**Issue by sergeda** [scalapb/zio-grpc#492]
There is no example how to use client's Metadata in webapp in fullApp example.
I tried to use it, but looks like it's not implemented yet:
```
final class Metadata {
  def get[T](key: Metadata.Key[T]): T = ???

  def put[T](key: Metadata.Key[T], value: T): Unit = ???

  def remove[T](key: Metadata.Key[T], value: T): Boolean = ???
}

object Metadata {
  final class Key[T]
}

```

**Comment by dejvid** [comment]
Yes I was wondering the same thing.

**Comment by thesamet** [comment]
Are you looking to be able to send metadata from the browser to the server, or the other way around? Sending from the browser needs to be added and would be fairly straightforward. In the other direction, I'm not if it's supported in grpc-web.

**Comment by sergeda** [comment]
@thesamet I'm looking for a way to send metadata from the browser to the server

**Comment by thesamet** [comment]
With v0.6.0-rc5 there's a simple API to create metadata out of pairs of strings in both JS and JVM. See usage example in ea7ceaf.

**Comment by sergeda** [comment]
Thank you @thesamet
