### ISSUE TITLE
Transform error type

### ISSUE THREAD

**Issue by regiskuckaertz** [scalapb/zio-grpc#500]
Hello

The `StatusException` data type is not very practical to handle in business logic, usually what we do is introduce a custom error type and transform at the end of the world (usually in a "lossy" fashion). With that in mind, it would be great to add the ability to transform the error type, just like it is possible to transform the requirement:

```scala
trait ZTransform[+CtxIn, -CtxOut, -ErrIn, +ErrOut] {
  def effect[A](io: CtxIn => IO[ErrIn, A]): CtxOut => IO[ErrOut, A]
  def stream[A](io: CtxIn => Stream[ErrIn, A]): CtxOut => Stream[ErrOut, A]
}

object ZTransform {
  def mapError[Ctx, Ctx, ErrIn, ErrOut](f: ErrIn => ErrOut): ZTransform[Ctx, Ctx, ErrIn, ErrOut] = ???
  def mapErrorZIO[Ctx, Ctx, ErrIn, ErrOut](f: ErrIn => IO[ErrOut, ErrOut]): ZTransform[Ctx, Ctx, ErrIn, ErrOut] = ???
}
```

**Comment by thesamet** [comment]
heads up that I have some wip to support this feature request.

**Comment by regiskuckaertz** [comment]
Fantastic! I moved to another project and am spending less time with gRPC right now but very keen to keep helping when I can.
