### ISSUE TITLE
Unexpected behaviour when using `ZStream` with `Deadline` in generated client

### ISSUE THREAD

**Issue by alexandrustana** [scalapb/zio-grpc#512]
Hello,

I've encountered an issue while bumping the version from **0.5.1** to **0.6.0-rc5**. 

Setting the `Deadline` behaves differently when in a streaming scenario. In version **0.6.0-rc5** it kills the stream after the deadline passed, even if data is passed through the stream. In the older version, **0.5.1**, it didn't kill the stream.

Doing some slight changes to the `example/fullapp` can show this scenario.
```scala
// ExampleServer.scala
  def points(
      request: Request,
      context: RequestContext
  ): Stream[StatusException, Point] = {
    val res = ZStream
      .iterate(Point(0, 0))(i => Point(i.x + 1, i.y + 1))
      .schedule(Schedule.spaced(500.millis))
```
```scala
// ExampleClient.scala
  def clientLayer: Layer[Throwable, GreeterClient] =
    GreeterClient.live(
      ZManagedChannel(
        ManagedChannelBuilder.forAddress("localhost", 9000).usePlaintext()
      ),
      CallOptions.DEFAULT.withDeadlineAfter(10, TimeUnit.SECONDS)
    )

  def myAppLogic =
    (for {
      _ <- Clock.instant.tap(t => printLine(s"Started $t"))
      _ <- GreeterClient.points(Request("Hello")).tap(point => printLine(point)).runCollect
      _ <- Clock.instant.tap(t => printLine(s"Stopped $t"))
    } yield ())
      .onError(c => printLine(c.prettyPrint).orDie)
      .provideLayer(clientLayer)
```
Making the above changes will result in a `DEADLINE_EXCEEDED` exception after 10 seconds have passed.

Is this behaviour intended?

**Comment by thesamet** [comment]
Thanks for reporting. Interestingly, even if the server sends no data (change `def points(...)` to return `ZStream.never`, there would be no timeout in 0.5.1. So it looks like streams are not interrupted at all in 0.5.1 regardless of whether there is a response or not.

The behavior you see currently at 0.6.x is the expected one -  the deadline controls the entire runtime of the request. It does not reset with every message that is received. zio-grpc is built on top of grpc-java, so while I wasn't able to find any documentation that describes it, it does appear to be consistent with this https://github.com/grpc/grpc-java/issues/4814

I believe the desired behavior can be achieved using `ZClientInterceptor` by following the lines of the example linked from the issue: https://github.com/carl-mastrangelo/grpc-java/commit/4a31a589c98f5f9c6f87206a6cb3c8d43b136924
