### ISSUE TITLE
The tutorial is out of date

### ISSUE THREAD

**Issue by omidb** [scalapb/zio-grpc#517]
The tutorial is out of date with the current API.

**Comment by thesamet** [comment]
Are you switching the version to 0.6.x at the top right of the page?

**Comment by omidb** [comment]
I wasn't. Is there any plan to have a new release? There are some other comments out there: https://github.com/LesnyRumcajs/grpc_bench/pull/349

**Comment by thesamet** [comment]
I am not sure why the code there has been removed, it has nothing to do with API changes, but this is true. We don't have 0.6.x since we haven't finalized the API yet and a few more changes are coming before it's 0.6.0.
