### ISSUE TITLE
Struggling with composing dependency requirements in transformContext

### ISSUE THREAD

**Issue by frekw** [scalapb/zio-grpc#52]
Hi!

I'm working on integrating tracing into an app and have stumbled into two challenges:

When a request hits my application, I'd ideally want to extract incoming trace headers and setup a span based on headers in `Metadata`. The best way of doing that (which is what https://github.com/zio/zio-telemetry is doing) would be to be able to do so in a `ZManaged` to make sure the span is always ended no matter what happens during the duration of the request. Since `transformContext` returns a transformed `IO[Status, R]` that currently won't work.

My other attempt was to extract the root span information and return a `Has[SpanContext]` from `transformContext` and use that downstream. Not as elegant but absolutely doable. However, I also need some other dependencies setup downstream (such as the current user) and I can't figure out a way to make `transformContext` return `IO[Status, Has[SpanContext] with Has[CurrentUser]`.

One solution that I've instinctively thought of that would solve composition, as well as brackets, would be to change

```scala
def transformContext[R <: Has[_], E, Context1 <: Has[_]: Tagged, Context2 <: Has[_]: Tagged](
  f: Context2 => ZIO[R, E, Context1]
)
```

to something like

```scala
def transformContext[R <: Has[_], E, Context1 <: Has[_]: Tagged, Context2 <: Has[_]: Tagged](
  f: Context2 => ZLayer[-R, E, +R]
)
```

but I'm not quite sure what the actual implications of doing that would be, if it's at all possible.

I'd be happy to investigate it further if you can provide me with some pointers!

**Comment by thesamet** [comment]
Hi @frekw , sounds like this is a use case that we should support and have documentation for, so thanks for filing the issue and starting the discussion.

Let's make sure you are working with the latest snapshot, we added support for passing context in the environment.

I think that the ZIO way would be to have `Has[SpanContext] with Has[CurrentUser]` passed down in the environment. If you prefer this to be passed as an explicit parameter you can look into the `WithContext` variant.

To ensure that SpanContext is closed, you can look into the `transform` method. This is a way to apply the same transformation on all your rpc methods. You provide this method with a `ZTranform` that is merely a recipe for transforming your RPC handlers. That ZTranform can invoke `bracketExit` on the IO to ensure the span is finished.

Can you try and let me know if this is helpful? Happy to dig in to the zio-telemetry if that would be helpful.

**Comment by frekw** [comment]
Hi @thesamet 

Right now I'm on [this snapshot](https://github.com/scalapb/zio-grpc/commit/55ce710412a366aa03a5b0d4956a2851e0c949a8) and using the new `Z`-flavour of the API, with environment support. The reason why I'm not on the latest snapshot is because I'm still using `RC18-2`.

> I think that the ZIO way would be to have Has[SpanContext] with Has[CurrentUser] passed down in the environment. If you prefer this to be passed as an explicit parameter you can look into the WithContext variant.

Yes, I absolutely agree. I think what's tripping me up a bit in this case is that my understanding of how one goes about providing the environment's dependencies is through `ZLayer` and I'm not completely sure how I can do it in other ways.

This is more or less what I'm struggling with:

```
import zio._
import zio.logging._
import app.database._

type APIEnv =
    Random
      with Logging
      with Database

type Interceptors = Has[CurrentUser] with Has[RemoteSpan]


val tracingLayer: ZLayer[Has[RemoteSpan], Nothing, Tracing] = ZLayer.fromEffect(
  ZIO.access[Has[RemoteSpan]](_.get).flatMap(new Tracing(_))
)

object LiveService extends ZAPI[APIEnv, Interceptors] {
  def unaryCall(request: UnaryRequest): ZIO[APIEnv with Interceptors, Status, UnaryResponse] =     
    val eff: ZIO[APIEnv with Tracing, Status, UnaryResponse] = ???
    eff.provideSomeLayer[APIEnv](tracingLayer)
  }
}

def currentUser(m: Metadata): IO[Status, User] = ???
def remoteSpan(m: Metadata): IO[Status, RemoteSpan] = ???

val live: ZLayer[APIEnv, Nothing, Has[ZAPI[Any, Has[Metadata]]]] = ZAPI.toLayer(ZAPI.transformContext(LiveService, (m: Metadata) =>
  // ideally I'd like to return Has[CurrentUser] + Has[RemoteSpan] here, but I can't figure out how I can actually compose the two values
  // I insinctively thought Has[CurrentUser](currentUser) ++ Has[RemoteSpan](remoteSpan) would
  // work, but I couldn't get that to compile
  ZIO.mapParN(currentUser(m), remoteSpan(m), ((currentUser, remoteSpan) => ??? /* not sure what to return here */)
)
}
```

If I get the above to work, I could extract the `RemoteSpan` in the `ZAPI` implementation and create an instance of a `Tracing` service in each RPC handler. A bit fiddly but absolutely doable.

What would be easier (at least in my case), would be if I could do something like the following, since it would simplify both the layer creation/release as well as make the environmental dependencies clearer (i.e my handler needs a `Tracing`-service and not really a `SpanContext`).
```
import zio._
import zio.logging._
import app.database._

type APIEnv =
    Random
      with Logging
      with Database

type Interceptors = Has[CurrentUser] with Has[Tracing]

object LiveService extends ZAPI[APIEnv, Interceptors] {
  def unaryCall(request: UnaryRequest): ZIO[APIEnv with Interceptors, Status, UnaryResponse] = ???
}

def currentUser(m: Metadata): ZLayer[Any, Status User] = ???
def tracing(m: Metadata): ZLayer[Any, Status, Tracing] = ???

val live: ZLayer[APIEnv, Nothing, Has[ZAPI[Any, Has[Metadata]]]] = ZAPI.toLayer(ZAPI.transformContext(LiveService, (m: Metadata) =>
  // ZLayer[Metadata, Status, Has[User] with Has[RemoteSpan]], would make sure
  // would also make sure that the tracing layer is released properly after the request finishes.
  curentUser(m) ++ tracing(m)
)
}
```

Hopefully that makes it a bit clearer what I'm trying to do I'll investigate using `transform` with `bracketExit` more tonight!

**Comment by frekw** [comment]
Hey again!

Just wanted to loop back to this and say that your `transform` proposal works splendidly, after managing to figure out how the types for `transform` and  `ZTransform` suppose to map to one another.

I ended up with this:

```scala
type APIEnv =
    Random
      with Logging
      with Database

type Interceptors = Has[Viewer] with Tracing

object LiveService extends ZAPI[APIEnv with Interceptors, Any] {
  def unaryCall(request: UnaryRequest): ZIO[APIEnv with Interceptors, Status, UnaryResponse] = ???
}

def currentUser: ZLayer[Has[Metadata], Status User] = ???
def tracing: ZLayer[Has[Metadata], Status, Tracing] = ???

val live: ZLayer[APIEnv, Nothing, Has[ZAPI[Any, Has[Metadata]]]] = 
ZAPI.toLayer(
      ZAPI.transform[APIEnv with Interceptors, Any, APIEnv, Has[Metadata]](
        LiveService,
        ZTransform[APIEnv with Interceptors, Status, APIEnv with Has[Metadata]] {
          def effect[A](
              io: ZIO[APIEnv with Interceptors, Status, A]
          ): ZIO[APIEnv with Has[Metadata], Status, A] = {
             io.provideSomeLayer[APIEnv with Has[Metadata]](viewerLayer ++ tracing)
          }
          def stream[A](
              io: ZStream[APIEnv with Interceptors with Any, Status, A]
          ): ZStream[APIEnv with Has[Metadata], Status, A] = ???
        }
      )
    )
```

Now onto my next question, ideally I'd like to be able to extract the `getMethodDescriptor()` from the `io.grpc.ServerCall` to be able to automatically annotate the root span for each request appropriately. Currently I can't seem to find any escape hatches to access this, but I _think_ it could be as easy as changing `server*CallHandlerR` to do provide the request itself along with the metadata, and either doing some appropriate translation in `ZServerCall`, or just allow access to the raw, underlying `io.grpc.ServerCall` as an escape hatch. What do you think?

Once I'm finished with all of this I'd be more than happy to contribute a fully working example, since I think it could be very useful for others in the future.

**Comment by thesamet** [comment]
I introduced a new `RequestContext` which you can get through the environment, that contains `Metadata`, as well as the current `MethodDescriptor` and a few other things I found in `io.grpc.ServerCall`.

**Comment by frekw** [comment]
Amazing, thank you! 🙏 🙏 🙏
