### ISSUE TITLE
Being able to set Metadata per outgoing RPC

### ISSUE THREAD

**Issue by frekw** [scalapb/zio-grpc#59]
Hi (again)! :)

I'd like to be able to set metadata, or more specifically headers, per outgoing RPC in order to propagate trace context headers to downstream gRPC services.

I _think_ doing this in a lot of real-world use cases would need to be effectful and is probable to have dependencies in the environment.

There are two approaches that I can think of:

1. Parameterising the `Client` on `R` and changing the calls to accept an effect which potentially overrides the default metadata, i.e:
```scala
trait Client[R] {
  def unaryCall(req: Request, metadata: Metadata => ZIO[R, Status, Metadata] = default => ZIO.succeed(default): IO[Status, Response]
}
```

2. Changing `Client.live`  to `def live(chan: ZManagedChannel, opts: CallOptions, headers: IO[Status, Metadata]`. I _think_ that would make it possible to get the needed dependencies by using `ZLayer.fromService(s)Managed`, creating the effect and then delegating to `Client.managed(chan options, headersEffect)`. This seems easier, but less flexible (without introducing a parameter like the `RequestContext` as input to the effect that creates the headers).

Which approach do you think is the best? I'd be happy to jump in and help!

**Comment by thesamet** [comment]
Hi @frekw ,

Another approach would optimize on symmetry with what we added recently to the server side:
3. The client would read the Metadata (or a context object) from the environment. Then run an effect to convert the context into Metadata. If you are writing a server that calls upstream backends, it would enable wiring through the headers implicitly.

I am not sure how I understand how (2) would work: how's the header effect determine the headers for each client call?

**Comment by frekw** [comment]
For (2) I'm thinking that it wouldn't really allow you to specify custom headers on a per-request, rather only making sure that you can effectfully update the metadata on a per request basis (i.e you could use stateful using `FiberRef`s under the hood to keep and set and propagate some local request state). So it's definitely an inferior solution technically speaking.

I think (3) sounds like a really cool approach to try out! I guess each service would have its own `Context` to keep the 1:1 mapping between the server and the client, so conflicts between multiple APIs shouldn't really be an issue.

The only limitation I can think of would be that it would be hard to set per-request headers for the same RPC from the same session unless you could provide the `Context => Metadata` effect as a parameter per RPC call. But that's a limitation of my proposals as well, and likely a quite unusual edge case.

All in all I think (3) is more inline with ZIO, and provides better symmetry between the APIs, as you say.

> Re (1) I am consider removing the WithContext[R] trait that gives context as a parameter in favor of the environment-based solution, so there are fewer variations to worry about at this early stage of the project.

I think that makes a lot of sense. It doesn't provide anything that the environment based solution doesn't already.

**Comment by thesamet** [comment]
The main thing that I am concerned about with (3) is users unintentionally passing metadata to an upstream client while implementing a server when they reuse the same Context object. But I think it's a good first try. Would you be interested in putting together a PR?

**Comment by frekw** [comment]
@thesamet I'd be more than happy to give it a try tomorrow!

**Comment by frekw** [comment]
Hey!

I threw together a very rough PR just to get an idea of how actual use could work. I think the important part is: https://github.com/scalapb/zio-grpc/blob/8f1e0c40f65e4a133be329d5953357d9052c622c/e2e/src/test/scala/scalapb/zio_grpc/ContextSpec.scala#L87-L95

Where you could provide a mapping function from the environment to the request (if you were to require the same context as you'd extract from an incoming request it would feel very similar to a contramap), while making it pretty easy both provide and override defaults.

Was that what you had in mind? If so I'd be happy to try to refactor the mess I introduced in the code generator!

**Comment by thesamet** [comment]
Thanks for putting this together so quickly. I'll take a closer look tonight.

**Comment by thesamet** [comment]
I am also trying to see if we can port the concept of ClientInterceptors from grpc-java. Can you try this on the latest snapshot? https://github.com/scalapb/zio-grpc/commit/6c72b82be2c9bba8833dba8bbbab9a47c54e9e96#diff-5d3ebbe8feb185093f212a10d3f55afbR80-R89 

The idea is that we add an interceptor on the channel, before an RPC is sent, you get a chance to run an effect to replace the metadata, as a function of the MethodDescriptor, CallOptions and the environment.

**Comment by frekw** [comment]
Awesome! 🙏

It seems to be working, this is pretty much what I ended up with:

```scala
    val AuthorizationKey =
    Metadata.Key.of("Authorization", Metadata.ASCII_STRING_MARSHALLER)
  lazy val format = HttpPropagationUtil.getCloudTraceFormat()
  val setter: TextFormat.Setter[Metadata] = (carrier, rawKey, value) => {
    val key = Metadata.Key.of(rawKey, Metadata.ASCII_STRING_MARSHALLER)
    carrier.put(key, value)
  }

  def live(cfg: config.ServiceConfig) =
    ZLayer.fromServiceManaged[
      Tracing.Service,
      Any,
      Throwable,
      ServiceClient.Service
    ] { (tracingService) =>
      val layer = ZLayer.succeed(tracingService)
      val headerInterceptor =
        ZClientInterceptor.metadataReplacer[Any](
          (_: MethodDescriptor[_, _], _: CallOptions) =>
            (for {
              md <- UIO(new Metadata)
              _ <- UIO(md.put(AuthorizationKey, s"Basic ${cfg.auth}"))
              _ <- tracing.inject(format, md, setter)
            } yield md)
              .provideLayer(layer)
        )

      ServiceClient.managed[Any](
        ZManagedChannel(
          ManagedChannelBuilder
            .forAddress(cfg.host, cfg.port)
            .userAgent("backend-service"),
          Seq(headerInterceptor)
        )
      )
    }
```

and then wire it like:

```scala
val tracing = Tracing.live
val service = tracing >>> service.Client.live(conf.service) >>> service.Service.live
```

Without the call to `provideLayer` from within the interceptor, the environment/implementation details ends up leaking all over the place (e.g all accessors break), which I'm not sure you'd want.

I'm not sure we actually need the `ZService[R]`, I think just keeping it as a single `Service` would be fine, and then pushing all the wiring/environmental stuff to the env/ZLayer when instantiating the channel itself.

**Comment by thesamet** [comment]
I added a few improvements that should make it easier to code for this use case:
1. you can use `def live` defined on the generated service to create a `ZLayer[Tracing, Throwable, ServiceClient]` - no need to go through `fromServiceManaged`. 

2. Introduced[ `SafeMetadata`](https://github.com/scalapb/zio-grpc/blob/0f13162ec30c125d67ecfd665bf59e138e5e774e/core/shared/src/main/scala/scalapb/zio_grpc/SafeMetadata.scala) that allows you to mutate `Metadata` safely and effectfully.

**Comment by frekw** [comment]
@thesamet nice, that cleans things up quite a bit.

Good catch on the `SafeMetadata`!

I'll try to put together an end-to-end example in [zio-telemetry](https://github.com/zio/zio-telemetry) sometime this week!

**Comment by thesamet** [comment]
I believe this is fully resolved at this point.
