### ISSUE TITLE
Sample Projects use old version

### ISSUE THREAD

**Issue by domdorn** [scalapb/zio-grpc#599]
In hope of finding interesting clues for migrating my app, I looked at the sample applications.
Sadly, the sample applications are not using the current version of this lib but an older one, so are of no use. 
The sample applications should always use the latest version of the lib.

**Comment by thesamet** [comment]
Sample projects have been on 0.6.0-rc6, which is nearly identical to 0.6.0. I have bumped up the examples to 0.6.1 and no code change was necessary.
