### ISSUE TITLE
Release 0.6.2?

### ISSUE THREAD

**Issue by ghostdogpr** [scalapb/zio-grpc#623]
Hi @thesamet !

Would it be possible to release a 0.6.2? There are a few fixes (in particular https://github.com/scalapb/zio-grpc/pull/612 and https://github.com/scalapb/zio-grpc/pull/614) and improvements that would be great to have not just as snapshots 😄 

Thanks!

**Comment by thesamet** [comment]
Sure, kicked off a release for 0.6.2.
