### ISSUE TITLE
Memory leak in Stream.merge in ZIO RC-18-2

### ISSUE THREAD

**Issue by fillson-shady** [scalapb/zio-grpc#63]
Hello!

I faced huge memory leak - millions of FiberContext's are spawned (and not garbage collected) because of using Stream.merge method. Here is the [code](https://github.com/scalapb/zio-grpc/blob/master/core/jvm/src/main/scala/scalapb/zio_grpc/client/ClientCalls.scala#L139).
The problem became smaller in ZIO RC-19-2, however there is still small [leak](https://github.com/zio/zio/issues/3679).

Do you have a plans to migrate to ZIO RC-19-2?

Thank you!

**Comment by thesamet** [comment]
Yes, we're blocked by https://github.com/zio/zio/issues/3609 and having a release that contains the fix of https://github.com/zio/zio/issues/3660.

**Comment by thesamet** [comment]
Hi @fillson-shady , I've just merged ZIO-RC20

**Comment by ghostdogpr** [comment]
@thesamet do you plan doing an official release soon? Very happy about the recent changes exposing methodDescriptor and attributes!

**Comment by thesamet** [comment]
I've just released 0.3.0 which uses ZIO 1.0.0-RC20

**Comment by fillson-shady** [comment]
Great news, thank you @thesamet !
Have just switched to 0.3.0 without any difficulties.
It's seems that there is no any memory leaks for now, so I think the task may be closed?
zio/zio#3609 is not related with a memory leaks.

**Comment by thesamet** [comment]
Yes, #3609 is still impacting the current version, but not a show stopper. I'll document the impact of this issue on this project when I get a chance.
