### ISSUE TITLE
Release new version 0.6.3?

### ISSUE THREAD

**Issue by anika-apel** [scalapb/zio-grpc#664]
Hej @thesamet,
would it be possible to release 0.6.3? The improvements implemented with #574 are crucial as they do not only fix the retry mechanism but also ensure compatibility with the AWS ALB. With the current version (0.6.2) every error status code is transformed into an unknown server error.

**Comment by NavidJalali** [comment]
I am also waiting for the release

**Comment by thesamet** [comment]
I have released 0.6.3. Please note that there is a test that seems flaky due to recent changes. It would be great if someone can investigate and send a PR: https://github.com/scalapb/zio-grpc/actions/runs/11585386701/job/32254219139#step:7:195
